### ISSUE TITLE
Present 0.6.0 fails immediately on my machine

### ISSUE THREAD

**Issue by mauvedeity** [vinayak-mehta/present#120]
`present <file>` fails immediately on my systems, irrespective of the markdown file I call it on:
`% present example.md`

Steps used to install `present`:
1. `pip3 install present`

`% present example.md`

**Expected behavior**
I expected to see my first slide as defined in `example.md` on screen.

**Screenshots**
```
Traceback (most recent call last):
  File "/Users/rhys.wilkins/Library/Python/3.11/bin/present", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/present/cli.py", line 15, in cli
    slides = Markdown(filename).parse()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/present/markdown.py", line 39, in parse
    ast = markdown(text, renderer="ast")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/mistune/__init__.py", line 63, in markdown
    return md(text)
           ^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/mistune/markdown.py", line 104, in __call__
    return self.parse(s)[0]
           ^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/mistune/markdown.py", line 84, in parse
    result = self.render_state(state)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rhys.wilkins/Library/Python/3.11/lib/python/site-packages/mistune/markdown.py", line 45, in render_state
    return self.renderer(data, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object is not callable
```

**Environment**
Platform macOS-13.3.1-arm64-arm-64bit
Terminal emulator: Terminal.app
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
Present 0.6.0

**Additional context**
Can repro on Linux VM as well.

**Comment by domma** [comment]
Same for me. Obviously the mistune library has been updated and has breaking changes. It worked for me after removing mistune and manually installing `mistune<3`.

**Comment by rprosenc** [comment]
same for me :-(

**Comment by v4ld3rr4m4** [comment]
Thanks , efectivly . install 
``
pip` install mistune==2
``

**Comment by a4z** [comment]
> Thanks , efectivly . install `` pip` install mistune==2 ``

thanks!

**Comment by Hiruka-23** [comment]
The workarounds in the comments above are correct: mistune 3.x broke the renderer. Here is the root cause and the one-line formal fix, fully verified.

**Root cause:** `setup.py` declares `"mistune>=2.0.0a4"` with no upper bound. Today that resolves to mistune 3.3.4, whose AST redesign removed the `level` key the renderer reads, so every deck dies with `KeyError: 'level'` (effects.py:125). Unpatched 0.6.0 crashes on a fresh install on Python 3.11, 3.12 and 3.13.

**Fix** (`setup.py`, one line):
```diff
--- a/setup.py
+++ b/setup.py
@@ -18,1 +18,1 @@
-    "mistune>=2.0.0a4",
+    "mistune>=2.0.0a4,<3.0.0",
```

**Verified in my sandbox (end to end, not just unit):**
- AST of mistune 2.0.0a4 / 2.0.5 / 2.1.0 is identical for the tokens present renders: no renderer change needed across the whole 2.x line.
- Test harness across 8 slides and 15 element kinds (headings, bullets, code blocks, images, blockquotes...) renders identically on those three versions × Python 3.11/3.12/3.13.
- Terminal runs (pty) of a real deck exit 0 with the cap on all three Pythons; unpatched controls crash with `KeyError: 'level'` and exit 1.
- Patch applies cleanly to the released PyPI sdist (0.6.0), not just the repo checkout.

**Caveat found while testing (pre-existing, separate):** linebreak tokens inside paragraphs crash present on *every* mistune version (`NameError: 'Linebreak'`, Paragraph.render evaluates token names without fallback). It does not block the fix above, but it is the next bug anyone hits on complex decks — happy to file it separately.

Full write-up with evidence: https://ilands.ai/content/354410306971111424
Patch file: https://pub-a941bfd863a24f91a60e6c4979c18a84.r2.dev/pi-sandbox-uploads/354155310337757184/2026-09-04/1788565214513-db2aefc2-260c-440f-b662-3a0e1c994d68-present-mistune-cap.diff
