### ISSUE TITLE
italics terminfo field varies on different shells/oses

### ISSUE THREAD

**Issue by mitchgillin** [vinayak-mehta/present#48]
See attached error
![image](https://user-images.githubusercontent.com/23229682/91672837-c1aaa400-eafe-11ea-913a-d6b21f0faaf9.png)

OS: 10.15.6 (19G2021)
Shell: ZSH
Python: 3.8.5

**Comment by andrespagella** [comment]
Same problem here.

**Comment by agn-7** [comment]
Another problem is here when I ran a `README.md` by `present`:

```
> present README.md            

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/present/markdown.py", line 242, in parse
    Element = eval(element_name)
  File "<string>", line 1, in <module>
NameError: name 'Strong' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/present", line 8, in <module>
    sys.exit(cli())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/present/cli.py", line 18, in cli
    slides = markdown.parse(f.read())
  File "/usr/local/lib/python3.6/dist-packages/present/markdown.py", line 245, in parse
    f"(Slide {sliden + 1}) {element_name} is not supported"
ValueError: (Slide 2) Strong is not supported
```

---
OS: *Ubuntu 16.04*
Shell: zsh
*Python 3.6*

**Comment by vinayak-mehta** [comment]
@mitchgillin Thanks for reporting this! Looks like italics support varies on different shells, I'll look into this.

@agn-7 It should work for you if you're on Python 3.7+ and have present 0.5.0.

**Comment by vinayak-mehta** [comment]
This should be fixed with present v0.5.1, please reopen it if you still face the issue.

**Comment by mitchgillin** [comment]
Fixed for me! Thanks; can't wait to use it!

**Comment by vinayak-mehta** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
