### ISSUE TITLE
pip3 install present should install all dependencies

### ISSUE THREAD

**Issue by qcu** [vinayak-mehta/present#49]
# first issue - ModuleNotFoundError: No module named 'dataclasses'

```
$ pip3 install present 
$ present sample.md 
Traceback (most recent call last):
  File "/home/user/.local/bin/present", line 7, in <module>
    from present.cli import cli
  File "/home/user/.local/lib/python3.6/site-packages/present/cli.py", line 7, in <module>
    from .markdown import Markdown
  File "/home/user/.local/lib/python3.6/site-packages/present/markdown.py", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

resolved, obviously with: `pip3 install dataclasses`, however shouldn't this be listed in the README as a dependency or automatically installed with requirements.txt or some such?

# second issue - ValueError: (Slide 4) BlockQuote is not supported

```
$ present sample.md 
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/present/markdown.py", line 251, in parse
    Element = eval(element_name)
  File "<string>", line 1, in <module>
NameError: name 'BlockQuote' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/present", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/present/cli.py", line 18, in cli
    slides = markdown.parse(f.read())
  File "/home/user/.local/lib/python3.6/site-packages/present/markdown.py", line 254, in parse
    f"(Slide {sliden + 1}) {element_name} is not supported"
ValueError: (Slide 4) BlockQuote is not supported
```

**Comment by vinayak-mehta** [comment]
Re: first issue, you need to use Python 3.7 which has dataclasses in the standard library. I also thought that pip will handle it with [this line]https://github.com/vinayak-mehta/present/blob/master/setup.py#L53) in the `setup.py`. Python 3.7 is mentioned in the third badge on the README, but I guess I should also add a note about it.

Re: second issue, please install the latest version of present `0.5.0` from PyPI using `python3 -m pip install --upgrade present`.

**Comment by vinayak-mehta** [comment]
I've yanked older releases from PyPI, which means users get a warning if they install present on older Pythons. And also added a note on the README that `present` works only with Python >= 3.7.
