### ISSUE TITLE
No 'sample.md' found

### ISSUE THREAD

**Issue by Auhill** [vinayak-mehta/present#62]
Platform: Win 10
Version: Latest
Traceback: 
Traceback (most recent call last):
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\caibowei\AppData\Local\Programs\Python\Python37\Scripts\present.exe\__main__.py", line 7, in <module>
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\caibowei\appdata\local\programs\python\python37\lib\site-packages\present\cli.py", line 17, in cli
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sample.md'

Description:
Originally the trace was "ImportError: cannot import name '_CursesScreen' from 'asciimatics.screen' " and after I upgraded the package it became "No such file or directory"

**Comment by vinayak-mehta** [comment]
Hey, can you upgrade to the latest version `0.5.1`, `cd` into the examples directory, and then execute present? I think that should solve it.
