### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 32: illegal multibyte sequence

### ISSUE THREAD

**Issue by llvvrui** [vinayak-mehta/present#63]
D:\python\docs\report>present navicat.md
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\present.exe\__main__.py", line 7, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\present\cli.py", line 18, in cli
    slides = markdown.parse(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 32: illegal multibyte sequence

**Comment by vinayak-mehta** [comment]
Can you post your slides? (you can replace the text with lorem ipsum)

**Comment by llvvrui** [comment]
![Snipaste_2020-09-01_17-55-57](https://user-images.githubusercontent.com/38856163/91835774-6999ac00-ec7c-11ea-8922-bb513c301879.png)

**Comment by vinayak-mehta** [comment]
I meant can you post a text version which I can use to reproduce this bug and fix it?

**Comment by vinayak-mehta** [comment]
Closing due to inactivity, please open a new issue with some more details using the new template.
