### ISSUE TITLE
Cannot get it working

### ISSUE THREAD

**Issue by oesah** [vinayak-mehta/present#67]
Tried you sample.md, but it just throws errors for me.

Steps I took:

```
virtualenv --python=`which python3` venv
source venv/bin/activate
pip install present

present sample.md
```

Throws following error:
```
Traceback (most recent call last):
  File "/Users/Zentrale/IT/tmp/present/venv/bin/present", line 5, in <module>
    from present.cli import cli
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/present/cli.py", line 7, in <module>
    from .markdown import Markdown
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/present/markdown.py", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

When I install dataclasses manually with `pip install dataclasses`, the following error appears:

```
Traceback (most recent call last):
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/present/markdown.py", line 251, in parse
    Element = eval(element_name)
  File "<string>", line 1, in <module>
NameError: name 'BlockQuote' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Zentrale/IT/tmp/present/venv/bin/present", line 8, in <module>
    sys.exit(cli())
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/present/cli.py", line 18, in cli
    slides = markdown.parse(f.read())
  File "/Users/Zentrale/IT/tmp/present/venv/lib/python3.6/site-packages/present/markdown.py", line 254, in parse
    f"(Slide {sliden + 1}) {element_name} is not supported"
ValueError: (Slide 4) BlockQuote is not supported
```

Any idea?

**Comment by vinayak-mehta** [comment]
`present` only works with Python 3.7+.  I think you might be on Python 3.6. Can you make a venv with Python3.7 and install `present` 0.5.1? That should do the trick :smile:
