### ISSUE TITLE
Error in running it

### ISSUE THREAD

**Issue by VasudevGupta7** [vinayak-mehta/present#68]
When I am trying to use this package in Mac OS, Its showing this error:

```
Traceback (most recent call last):
                                    File "/Users/vasudevgupta/miniconda3/envs/insights/bin/present", line 8, in <module>
                                                                                                                            sys.exit(cli())
                                                                                                                                             File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/click/core.py", line 829, in __call__
                                                                                   return self.main(*args, **kwargs)
                                                                                                                      File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/click/core.py", line 782, in main
                                                        rv = self.invoke(ctx)
                                                                               File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
                    return ctx.invoke(self.callback, **ctx.params)
                                                                    File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
                                          File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/present/cli.py", line 20, in cli
                                                                                                                                                             with Slideshow(slides) as show:
            File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/present/slideshow.py", line 90, in __enter__
                                                                                                                                           self.screen = Screen.open()
                                                                                                                                                                        File "/Users/vasudevgupta/miniconda3/envs/insights/lib/python3.7/site-packages/asciimatics/screen.py", line 1294, in open
                                                                                                                   curses.cbreak()
                                                                                                                                  _curses.error: cbreak() returned ERR
```

What can be the possible reason??

Thanks

**Comment by vinayak-mehta** [comment]
Try running it with `TERM='xterm-256color' present slides.md`? I would recommend trying it on another terminal emulator.

**Comment by VasudevGupta7** [comment]
I tried it. same error occurred.

**Comment by vinayak-mehta** [comment]
Which terminal emulators did you try on? I don't have a macOS machine to test, but maybe I can install those terminal emulators and see if it works on them.

**Comment by vinayak-mehta** [comment]
@VasudevGupta7 I also added a [contributor's guide](https://present.readthedocs.io/en/latest/contributing.html#contributing). Can you read through the filing issues section and provide some more info that's listed there?

**Comment by vinayak-mehta** [comment]
Closing due to inactivity, please reopen if you still face the issue.

**Comment by 360er0** [comment]
I got the same error. I've tried both the build-in terminal and iTerm.

```
>>> import platform; print('Platform', platform.platform())
Platform Darwin-19.6.0-x86_64-i386-64bit
>>> import sys; print('Python', sys.version)
Python 3.7.7 (default, May  6 2020, 04:59:01)
[Clang 4.0.1 (tags/RELEASE_401/final)]
>>> import present; print('Present', present.__version__)
Present 0.5.1
```

**Comment by vinayak-mehta** [comment]
I'm not able to reproduce this as I don't have a MacOS machine. Could you try on another terminal emulator like guake and raise a new issue if you still face the bug?
